### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by wrongtarget00** [silentninjabee/Farlight84_iOS_SDK#2]
How can i make hack with it ?
What are offsets can i use?
Please help me if you can 
Iphone 11 pro max ios 15.4.1 jb dopamine

**Comment by wrongtarget00** [comment]
How can i use your aimbot project for farlight ?

**Comment by silentninjabee** [comment]
https://github.com/silentninjabee/iOS-IMGUI-Mod-Menu-Templates

And

https://youtu.be/9-PfvPDgyPI?si=sSeKsNS8nMIetVyC
